import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

/**
 * Evaluate user input
 */
public final class DobbyLogic {
    /** Initialize dictionary of commands */
    enum Command {
        LIST,
        MARK,
        UNMARK,
        TODO,
        DEADLINE,
        EVENT
    }
    private static final Map<String, Command> COMMANDS = new HashMap<>();
    static {
        for (Command command : Command.values()) {
            COMMANDS.put(command.name().toLowerCase(Locale.ROOT), command);
        }
    }

    /** Store tasks recorded since the start of program */
    private final List<Task> tasks = new ArrayList<>();

    /**
     * Call appropriate methods or add task to input, depending on user command in input
     * @param input User command or task to be added
     */
    public void listen(String input) {
        // Split input into array of words, removing all spaces
        if (input.trim().isEmpty()) {
            print("> Dobby couldn't hear you. Dobby want you to speak louder!");
            return;
        }
        String[] inputs = input.trim().split("\\s+");
        Command command = COMMANDS.get(inputs[0].toLowerCase(Locale.ROOT));


        // Old way to instantiate tasks
        if (command == null) {
//            this.tasks.add(new Task(input));
//            print("> Dobby noted: " + input);
            print(" > Dobby asks is this a Todo, Deadline, or Event?");
            return;
        }

        switch (command) {
            case LIST:
                this.doList();
                break;

            case MARK, UNMARK:
                this.doMark(inputs, command);
                break;

            case TODO, DEADLINE, EVENT:
                this.createTask(inputs, command);
                break;
        }
    }

    public boolean isBye(String input) {
        return input.equalsIgnoreCase("bye");
    }

    /**
     * Print all tasks as numbered list
     */
    private void doList() {
        StringBuilder res = new StringBuilder();
        res.append("> Dobby show ").append(this.tasks.size()).append(" tasks:\n");
        int count = 0;
        for (Task t : this.tasks) {
            count++;
            res.append(count).append(". ").append(t).append("\n");
        }
        print(res.toString());
    }

    /**
     * Parse Mark & Unmark command, calls respective marking command
     * @param inputs [MARK/ UNMARK, int index]
     */
    private void doMark(String[] inputs, Command command) {
        // Check valid command arguments
        if (inputs.length != 2) {
            print("> Dobby is confused. Dobby think you meant '" + inputs[0] + " <Task number>'");
            return;
        }

        // Check valid index
        int i; // input task number have offset of +1, so -1 to get correct index
        try {
            i = Integer.parseInt(inputs[1]);
        } catch (NumberFormatException e) {
            print("> Dobby is confused. Dobby expected a task number");
            return;
        }
        if (i > this.tasks.size() || i <= 0) {
            print("> Dobby is confused. Dobby can't find task " + i);
            return;
        }

        // Toggle done status
        Task t = this.tasks.get(i - 1);
        if (command == Command.MARK) {
            t.markDone();
            print("> Dobby will mark this as done!");
            print("   " + t);
        } else {
            t.markNotDone();
            print("> Dobby will mark this as not done!");
            print("   " + t);
        }
    }

    /** (generated by Codex)
     * Creates a task from a tokenized command. Deadline descriptions end at '/by';
     * Event descriptions end at '/from', and their star times end at '/to'.
     *
     * @param inputs tokenized user input
     * @param command type of task to create
     */
    public void createTask(String[] inputs, Command command) {
        switch (command) {
            case TODO:
                this.createToDo(joinTokens(inputs, 1, inputs.length));
                break;

            case DEADLINE:
                createDeadlineFromInput(inputs);
                break;

            case EVENT:
                createEventFromInput(inputs);
                break;

            default:
                // Shouldn't reach here
                throw new IllegalArgumentException("Unsupported task command: " + command);
        }
    }

    /** Creates a deadline after extracting its description and due date. */
    private void createDeadlineFromInput(String[] inputs) {
        int byIndex = this.findMarker(inputs, "/by", 1);
        if (byIndex == -1 || byIndex == 1 || byIndex == inputs.length - 1) {
            print("> Dobby is confused. Dobby think you meant 'deadline <description> /by <date/time>'");
            return;
        }
        createDeadline(this.joinTokens(inputs, 1, byIndex),
                this.joinTokens(inputs, byIndex + 1, inputs.length));
    }

    /** Creates an event after extracting its description, start time, and end time. */
    private void createEventFromInput(String[] inputs) {
        int fromIndex = this.findMarker(inputs, "/from", 1);
        int toIndex = this.findMarker(inputs, "/to", fromIndex + 1);
        if (fromIndex == -1 || toIndex == -1 || fromIndex == 1
                || fromIndex + 1 == toIndex || toIndex == inputs.length - 1) {
            print("> Dobby is confused. Dobby think you meant "
                    + "'event <description> /from <date/time> /to <date/time>'");
            return;
        }
        createEvent(this.joinTokens(inputs, 1, fromIndex), this.joinTokens(inputs, fromIndex + 1, toIndex),
                this.joinTokens(inputs, toIndex + 1, inputs.length));
    }

    /** Returns the index of a marker, or -1 when it is absent. */
    private int findMarker(String[] inputs, String marker, int startIndex) {
        for (int i = Math.max(0, startIndex); i < inputs.length; i++) {
            if (marker.equalsIgnoreCase(inputs[i])) {
                return i;
            }
        }
        return -1;
    }

    /** Joins tokens in the half-open range [start, end) with spaces. */
    private String joinTokens(String[] inputs, int start, int end) {
        String[] selectedTokens = new String[end - start];
        System.arraycopy(inputs, start, selectedTokens, 0, selectedTokens.length);
        return String.join(" ", selectedTokens);
    }

    public void createToDo(String str) {
        this.tasks.add(new ToDo(str));
        print("> Dobby noted a new Todo: " + str);
    }

    /** Adds a deadline with its due date/time. */
    public void createDeadline(String description, String by) {
        this.tasks.add(new Deadline(description, by));
        print("> Dobby noted a new Deadline: " + description + " by " + by);
    }

    /** Adds an event with its start and end date/time. */
    public void createEvent(String description, String from, String to) {
        this.tasks.add(new Event(description, from, to));
        print("> Dobby noted a new Todo: " + description + " from " + from + " to " + to);
    }

    private void print(String str) {
        DobbyUtil.print(str);
    }
}
